version: '2'

services:
  mongodb:
    image: "deeweeapp_mongodb"
    ports:
     - "27017:27017"
  backend:
    build: ./dockerserver/
    ports:
      - "3000:3000"
    volumes:
      - ./dockerserver:/usr/src/app/server/
    depends_on:
      - mongodb
  frontend:
    build: ./dockerclient/
    ports:
      - "8000:8000"
    volumes:
      - ./dockerclient:/usr/src/app/client/
    depends_on:
      - backend
