version: '2'

services:
  mongodb:
    image: mongo
    ports:
     - "27017:27017"
  backend:
    build: ./dockerserver/
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
  frontend:
    build: ./dockerclient/
    ports:
      - "8000:8000"
    depends_on:
      - backend
